CC = gcc
CXX = g++
CFLAGS = 
TARGET = thmbem.exe
INC = d:/mygnulib
MYLIB = d:/mygnulib
#OBJS : mainunit.o bemunit.o inputunit.o 
MYOBJS : $(MYLIB)/mymatrix.o $(MYLIB)/myint.o $(MYLIB)/myfloat.o

.SUFFIXES : .cpp .o

all : $(MYOBJS) $(TARGET) 

.PHONY : all clean 

$(TARGET) : $(MYOBJS)
	$(CC) -o $(TARGET) -I$(INC)  $(MYOBJS) -lm  # $(OBJS)

$(MYOBJS): .o : %.cpp
	$(CXX) -c $(CLFAGS) -I$(INC) $< -o $@ 
	
clean :
	-rm $(OBJS)